<!-- Generated by xAI Grok (model: gpt-5.4) during provisioning. Edit freely. -->
<script setup lang="ts">
</script>

<template>
  <div>
    <header class="bg-neutral-50 border-b">
      <UContainer class="py-4 flex items-center justify-between">
        <NuxtLink to="/" class="text-xl font-bold text-primary">Quick Domain Check</NuxtLink>
        <UNavigationMenu>
          <UNavigationMenuList>
            <UNavigationMenuItem>
              <NuxtLink to="/features">Features</NuxtLink>
            </UNavigationMenuItem>
            <UNavigationMenuItem>
              <NuxtLink to="/pricing">Pricing</NuxtLink>
            </UNavigationMenuItem>
            <UNavigationMenuItem>
              <NuxtLink to="/contact">Contact</NuxtLink>
            </UNavigationMenuItem>
          </UNavigationMenuList>
        </UNavigationMenu>
      </UContainer>
    </header>
    <slot />
  </div>
</template>