<!-- Generated by xAI Grok (model: gpt-5.4) during provisioning. Edit freely. -->
<script setup lang="ts">
import { useSeo, useWebPageSchema } from '#imports'
const appName = 'Quick Domain Check'
const appDescription = 'A tool for checking if domains are available'

useSeo({
  title: appName,
  description: appDescription,
  ogImage: {
    title: appName,
    description: appDescription
  }
})
useWebPageSchema({
  name: appName,
  description: appDescription
})

const features = [
  {
    icon: 'i-lucide-search',
    title: 'Instant Checks',
    description: 'Quickly verify domain availability across multiple TLDs.'
  },
  {
    icon: 'i-lucide-zap',
    title: 'Lightning Fast',
    description: 'Get results in seconds with our optimized search engine.'
  },
  {
    icon: 'i-lucide-shield-check',
    title: 'Reliable Results',
    description: 'Accurate and up-to-date information from trusted registries.'
  }
]
</script>

<template>
  <UContainer class="min-h-screen flex flex-col">
    <section class="py-20 text-center flex-1 flex flex-col justify-center">
      <h1 class="text-5xl font-bold mb-4 text-primary">{{ appName }}</h1>
      <p class="text-xl text-neutral-600 mb-8">{{ appDescription }}</p>
      <UCard class="max-w-md mx-auto">
        <template #header>
          <div class="flex items-center justify-center gap-2">
            <UIcon name="i-lucide-search" class="text-2xl text-primary" />
            <span class="font-semibold">Check a Domain</span>
          </div>
        </template>
        <form class="flex gap-2">
          <input type="text" placeholder="Enter domain name" class="flex-1 px-4 py-2 border rounded-md" />
          <UButton color="primary" icon="i-lucide-arrow-right">Check</UButton>
        </form>
      </UCard>
    </section>

    <USeparator />

    <section class="py-16">
      <h2 class="text-3xl font-bold text-center mb-12">Why Choose Us?</h2>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <UCard v-for="feature in features" :key="feature.title" class="text-center">
          <template #header>
            <UIcon :name="feature.icon" class="text-4xl text-primary mb-4" />
            <h3 class="text-xl font-semibold">{{ feature.title }}</h3>
          </template>
          <p class="text-neutral-600">{{ feature.description }}</p>
        </UCard>
      </div>
    </section>

    <USeparator />

    <section class="py-16 text-center">
      <h2 class="text-3xl font-bold mb-4">Ready to Find Your Perfect Domain?</h2>
      <p class="text-xl text-neutral-600 mb-8">Start checking availability now!</p>
      <UButton color="primary" size="xl" icon="i-lucide-rocket">Get Started</UButton>
    </section>
  </UContainer>
</template>